#
# Copyright 2013-2019 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.15.3"
jdk:
  - oraclejdk11
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
install:
  - echo "test install"
script:
  - echo "test script"
env:
  global:
    - JHI_PROFILE=dev
    - JHI_RUN_APP=1
    - JHI_PROTRACTOR=0
    # if JHI_LIB_BRANCH value is release, use the release from Maven
    - JHI_LIB_REPO=https://github.com/jhipster/jhipster.git
    - JHI_LIB_BRANCH=release
    # if JHI_GEN_BRANCH value is release, use the release from NPM
    - JHI_GEN_REPO=https://github.com/jhipster/generator-jhipster.git
    - JHI_GEN_BRANCH=master
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - JHI_E2E_HEADLESS=true
    - JHI_SCRIPTS=$HOME/generator-jhipster/test-integration/scripts
  matrix:
    - JHI_APP=ngx-default JHI_PROFILE=prod JHI_PROTRACTOR=1

#----------------------------------------------------------------------
# Install all tools and check configuration
#----------------------------------------------------------------------
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Use this for Protractor
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Update NPM
  - npm install -g npm

#----------------------------------------------------------------------
# Install JHipster and generate project+entities
#----------------------------------------------------------------------
install:
  - $TRAVIS_BUILD_DIR/test-integration/scripts/10-install-jhipster-daily-builds.sh
  # copy samples
  - ls -al $TRAVIS_BUILD_DIR/test-integration/jdl-samples/
  # copy init-env
  # - cp $TRAVIS_BUILD_DIR/test-integration/scripts/00-init-env.sh /home/travis/generator-jhipster/test-integration/scripts/
  # generate project and entities
  # - $JHI_SCRIPTS/11-generate-entities.sh
  - $TRAVIS_BUILD_DIR/test-integration/scripts/12-generate-project.sh
  # - $JHI_SCRIPTS/13-replace-version-generated-project.sh

#----------------------------------------------------------------------
# Launch tests
#----------------------------------------------------------------------
script:
  - echo "/!\ WIP /!\ Launching test scripts"
  # - $JHI_SCRIPTS/21-tests-backend.sh
  # - $JHI_SCRIPTS/22-tests-frontend.sh
  # - $JHI_SCRIPTS/23-package.sh
  # - $JHI_SCRIPTS/24-tests-e2e.sh

#----------------------------------------------------------------------
# Cache
#----------------------------------------------------------------------
before_cache:
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-framework/
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-dependencies/
  - rm -rf $HOME/.m2/repository/io/github/jhipster/jhipster-parent/

#----------------------------------------------------------------------
# Notifications
#----------------------------------------------------------------------
notifications:
  slack:
    secure: GiPHcfSjEVpCcCrbtXpLNC6DmSE2rwWiZEyeQUYBJIMwezu3yn2F4+LbFstnMR/oVv/z7oJ7ALRc2qOIG1RinGnQ/bYDEB6r1uY5UCmTILkY+UCe5pJBkzKFnVWWXXIwVU6guTe/nVrEcTc7WOTwLBgs8rmEJyhEp0XWP8VHmKF85tTHcx5bHC9O+P0vZoiHh1tmShOCzkfureLS0M0nLO6AThTW+UWxtBy3T3G7g2+kRl5Yktm8OdPUIVqR8mZrFiLwk9W6y1mZi4eTwFoth9zLamNqUm2uJUg2y1FJBPeNnR7jYoMi+Muwrpwg/oiiM58C2AhrG0QBmeomn+EiiUmkmCgVkrvzWx67xHBT3sD0733FhDlh3PiV47H2yiLUB96sQ47NUk7jk1eKwN1YJIBzRQ6aY13IAqYJCFVlQ/kICFyMqpuWUBGEwjgmc86r3qRErVb8C+apqoHvhpnEVu9GUUxeWvmOjZOTMHemOk5RehBylzkUdH0PyFC1twoPQIO9t522iTH/jNSVVwsKR81/8EIXtaTUYJZkwKJC02CU+BpZTSz4VLlwZG3upjJ2XtFu1d+Fy5wC1i8rNkhTq3XAYbpVB7VPQtiW2IFFOUV7CTXPiNPa3YadgztCjaqma3pppS+BMLfKaAXNm5pD0aZ1lFt1d19EzQMLdc5U5DU=
