#
# Copyright 2013-2019 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    JHI_PROFILE: prod
    JHI_RUN_APP: 1
    JHI_ENTITY: jdl
    JHI_JDK: '11'
    # if JHI_LIB_BRANCH value is release, use the release from Maven
    JHI_LIB_REPO: https://github.com/jhipster/jhipster.git
    JHI_LIB_BRANCH: master
    # if JHI_GEN_BRANCH value is release, use the release from NPM
    JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
    JHI_GEN_BRANCH: master
    # specific config
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true
    JHI_E2E_HEADLESS: true
    JHI_LOCAL_SCRIPTS: $(Build.SourcesDirectory)/test-integration/jdl-scripts

  strategy:
    matrix:
      eureka-jwt-mysql-memcached:
        JHI_APP: eureka-jwt-mysql-memcached
        JHI_ENTITY: jdl
      eureka-jwt-mariadb-memcached:
        JHI_APP: eureka-jwt-mariadb-memcached
        JHI_ENTITY: jdl
      eureka-session-mysql-memcached:
        JHI_APP: eureka-session-mysql-memcached
        JHI_ENTITY: jdl
      eureka-session-mariadb-memcached:
        JHI_APP: eureka-session-mariadb-memcached
        JHI_ENTITY: jdl
      eureka-oauth2-mysql-memcached:
        JHI_APP: eureka-oauth2-mysql-memcached
        JHI_ENTITY: jdl
      eureka-oauth2-mariadb-memcached:
        JHI_APP: eureka-oauth2-mariadb-memcached
        JHI_ENTITY: jdl
      consul-jwt-mysql-memcached:
        JHI_APP: consul-jwt-mysql-memcached
        JHI_ENTITY: jdl
      consul-jwt-mariadb-memcached:
        JHI_APP: consul-jwt-mariadb-memcached
        JHI_ENTITY: jdl
      consul-session-mysql-memcached:
        JHI_APP: consul-session-mysql-memcached
        JHI_ENTITY: jdl
      consul-session-mariadb-memcached:
        JHI_APP: consul-session-mariadb-memcached
        JHI_ENTITY: jdl
      consul-oauth2-mysql-memcached:
        JHI_APP: consul-oauth2-mysql-memcached
        JHI_ENTITY: jdl
      consul-oauth2-mariadb-memcached:
        JHI_APP: consul-oauth2-mariadb-memcached
        JHI_ENTITY: jdl
  steps:
  - template: azure-template-plus.yml
