#
# Copyright 2018-2021 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Angular Gradle NoSQL
on:
  workflow_dispatch:
    inputs:
      jhiGenRepo:
        description: "JHipster repository url"
        default: "https://github.com/jhipster/generator-jhipster.git"
        required: false
      jhiGenBranch:
        description: "JHipster repository branch"
        default: "main"
        required: false
  schedule:
    - cron: "30 0 * * *"
env:
  JHI_RUN_APP: 1
  JHI_JDK: 11
  JHI_LIB_REPO: https://github.com/jhipster/jhipster-bom.git
  JHI_LIB_BRANCH: main
  JHI_GEN_REPO: ${{ github.event.inputs.jhiGenRepo || 'https://github.com/jhipster/generator-jhipster.git' }}
  JHI_GEN_BRANCH: ${{ github.event.inputs.jhiGenBranch || 'main' }}
  SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
  SPRING_JPA_SHOW_SQL: false
  JHI_DISABLE_WEBPACK_LOGS: true
  JHI_E2E_HEADLESS: true
  JHI_SCRIPTS: /home/runner/generator-jhipster/test-integration/scripts
  NG_CLI_ANALYTICS: "false"
  JHI_GITHUB_CI: true
  # https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
jobs:
  applications:
    name: ${{ matrix.app-type }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        node_version: [12.18.3]
        os: [ubuntu-latest]
        app-type:
          - gradle-ngx-mongodb
          - gradle-ngx-cassandra
          # - gradle-ngx-couchbase
          # - gradle-ngx-neo4j
        include:
          - app-type: gradle-ngx-mongodb
            entity: mongodb
            profile: prod
            war: 0
            e2e: 1
          - app-type: gradle-ngx-cassandra
            entity: cassandra
            profile: prod
            war: 0
            e2e: 1
          # - app-type: gradle-ngx-couchbase
          #   entity: couchbase
          #   profile: prod
          #   war: 0
          #   e2e: 1
          # - app-type: gradle-ngx-neo4j
          #   entity: neo4j
          #   profile: prod
          #   war: 0
          #   e2e: 1
    env:
      JHI_ENTITY: ${{ matrix.entity }}
      JHI_APP: ${{ matrix.app-type }}
      JHI_PROFILE: ${{ matrix.profile }}
      JHI_WAR: ${{ matrix.war }}
      JHI_E2E: ${{ matrix.e2e }}
    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Download latest chrome binary
        run: |
          sudo apt update
          sudo apt install google-chrome-stable
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - name: "TOOLS: display configuration"
        run: ./test-integration/scripts/01-display-configuration.sh
      - name: "TOOLS: configure tools installed by the system"
        run: ./test-integration/scripts/03-system.sh
      - name: "TOOLS: configure git"
        run: ./test-integration/scripts/04-git-config.sh
      #----------------------------------------------------------------------
      # Install JHipster and generate project+entities
      #----------------------------------------------------------------------
      - name: "GENERATION: install JHipster"
        run: ./test-integration/scripts/10-install-jhipster-daily-builds.sh
      - name: "GENERATION: entities"
        run: $JHI_SCRIPTS/11-generate-entities.sh
      - name: "GENERATION: project"
        run: $JHI_SCRIPTS/12-generate-project.sh
      - name: "GENERATION: replace version in generated project"
        run: $JHI_SCRIPTS/13-replace-version-generated-project.sh
      - name: "GENERATION: jhipster info"
        run: $JHI_SCRIPTS/14-jhipster-info.sh
      #----------------------------------------------------------------------
      # Launch tests
      #----------------------------------------------------------------------
      - name: "TESTS: Start docker-compose containers"
        run: $JHI_SCRIPTS/20-docker-compose.sh
      - name: "TESTS: backend"
        run: $JHI_SCRIPTS/21-tests-backend.sh
      - name: "TESTS: frontend"
        run: $JHI_SCRIPTS/22-tests-frontend.sh
      - name: "TESTS: packaging"
        run: $JHI_SCRIPTS/23-package.sh
      - name: "TESTS: End-to-End"
        run: $JHI_SCRIPTS/24-tests-e2e.sh
